name: mieml
channels:
  - defaults
  - conda-forge
dependencies:
  - h5py
  - keras-gpu=2.6.0
  - matplotlib=3.5.3
  - numpy=1.19
  - opencv=4.5.1
  - pandas=1.3.5
  - pillow=9.0.0
  - python
  - scikit-learn-intelex=2021.6.0
  - seaborn=0.12.2
  - spyder=5.2.2
  - tensorflow-gpu=2.6.0
